import type { Metadata } from 'next';
import './globals.css';
import { fonts } from '@/lib/fonts';

export const metadata: Metadata = {
  title: 'E-commerce Single Product',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-br'>
      <body className={`${fonts.inter.variable} antialiased`}>{children}</body>
    </html>
  );
}
